"""empty message

Revision ID: 2242a9ca0be5
Revises: 55b2cf7b119f
Create Date: 2021-03-28 07:14:03.611030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2242a9ca0be5'
down_revision = '55b2cf7b119f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_works',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('end_point_uri', sa.Text(), nullable=False),
    sa.Column('top_page_outline', sa.Text(), nullable=False),
    sa.Column('work_url', sa.Text(), nullable=True),
    sa.Column('work_picture_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_point_uri'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_works')
    # ### end Alembic commands ###
