"""empty message

Revision ID: 9f2633a071d1
Revises: 9888a76abf94
Create Date: 2021-04-14 00:41:19.391565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2633a071d1'
down_revision = '9888a76abf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_works', sa.Column('work_picture_thumbnail_url', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'my_works', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_works', type_='unique')
    op.drop_column('my_works', 'work_picture_thumbnail_url')
    # ### end Alembic commands ###
