version: '3'
services:
  flask:
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    image: 633999724589.dkr.ecr.us-west-2.amazonaws.com/portfolio-flask-backend_flask:latest
    container_name: portfolio-flask
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app/
    environment:
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DB_NAME: ${RDS_DB_NAME}
      FLASK_APP: '/usr/src/app/application:app'
    ports:
      - 5000:5000
    command: /bin/sh -c "/usr/src/app/init_db.sh && flask db migrate && flask db upgrade && gunicorn -c gunicorn_settings.py application:app"
  
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: 633999724589.dkr.ecr.us-west-2.amazonaws.com/portfolio-flask-backend_web:latest
    container_name: portfolio-web
    ports:
      - 80:80
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask