# Elastic Beanstalk 用の docker-compose.yml

version: '3'
services:
  flask:
    image: 633999724589.dkr.ecr.us-west-2.amazonaws.com/portfolio-flask-backend_flask:latest
    container_name: portfolio-flask
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app/
    environment:
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DB_NAME: ${RDS_DB_NAME}
      FLASK_APP: 'application:app'
      FLASK_CONFIG: ${FLASK_CONFIG}
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: eb-flask-docker-log
        awslogs-create-group: "true"
        awslogs-stream: flask
    command: /bin/sh -c "/usr/src/app/migrate.sh && gunicorn -c gunicorn_settings.py application:app"

  web:
    image: nginx
    container_name: portfolio-web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: eb-nginx-docker-log
        awslogs-create-group: "true"
        awslogs-stream: nginx
    depends_on:
      - flask
