version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: portfolio-db
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'pass'

  flask:
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: portfolio-flask
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app/
    environment:
      PROXY_HOST: ${PROXY_HOST}
      FLASK_CONFIG: 'development'
    ports:
      - 5000:5000
    expose:
      - 5000
    command: gunicorn -c gunicorn_settings.py application:app
    depends_on:
      - db
  
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: portfolio-web
    ports:
      - 81:81
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

volumes:
  database:
    driver: local
