version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: portfolio-db
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'develop'

  flask:
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    image: portfolio-flask-backend_flask:latest
    container_name: portfolio-flask
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app/
    environment:
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DB_NAME: ${RDS_DB_NAME}
      FLASK_APP: '/usr/src/app/application:app'
      FLASK_CONFIG: 'development'
    ports:
      - 5000:5000
    expose:
      - 5000
    command: /bin/sh -c "./init_db.sh && flask db migrate && flask db upgrade && gunicorn -c gunicorn_settings.py application:app"
    depends_on:
      - db
  
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: portfolio-web
    ports:
      - 81:81
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

volumes:
  database:
    driver: local
